### ISSUE TITLE
Session/Permissions issue pulling content from publish instance

### ISSUE THREAD

**Issue by ghowell15** [TWCable/grabbit#84] opened 2015-10-09 15:55 UTC
There appears to be an issue when trying to pull content with grabbit from a publish instance. We're specifically having an issue pulling workflows under the path (/etc/workflow/models). The nodes are never written and grabbit just times out.

It appears to be a permissions/session issue on publish. @sagarsane Please add any additional details.

**Comment by sagarsane** [comment] 2015-10-10 16:42
Thanks @ghowell15, the issue is that when Grabbit Client connects to Grabbit Server in a Publish to Publish grabbit job scenario, it is not authenticating correctly which is resulting in "anonymous" session created to send the data from Grabbit Server to Grabbit client. The fix for this will likely be in the way Grabbit Client authenticates to Grabbit Server (which is the work being done in the PR I referenced above)

**Comment by jdigger** [comment] 2015-10-15 13:01
I believe this was completed with #85. Can you confirm?

**Comment by sagarsane** [comment] 2015-10-15 15:25
Yeah it was.

**Closed by sagarsane** 2015-10-15 15:25 UTC
